services:
  - type: web
    name: museus-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: REDIS_URL
        fromService:
          type: redis
          name: museus-redis
          property: connectionString
    autoDeploy: true

  - type: redis
    name: museus-redis
    plan: starter # Altere para 'free' se aplicável na sua conta Render
