import { Router } from 'express';
import { prisma } from '../prisma.js';
import { authMiddleware, requireRole } from '../middleware/auth.js';
import { checkEntityOwnership, assertTenantOwnership } from '../utils/ownership.js';

const router = Router();

// GET /translations?workId=xxx — Get translations for a work (public)
router.get('/', async (req, res) => {
    try {
        const workId = req.query.workId as string;
        if (!workId) return res.status(400).json({ message: 'workId obrigatório' });
        const translations = await prisma.workTranslation.findMany({
            where: { workId },
            orderBy: { language: 'asc' }
        });
        res.json(translations);
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Erro ao buscar traduções' });
    }
});

// POST /translations — Create or update (admin)
router.post('/', authMiddleware, requireRole(['ADMIN', 'MASTER']), async (req, res) => {
    try {
        const tenantId = req.user!.tenantId;
        if (!tenantId) return res.status(400).json({ message: 'tenantId obrigatório' });
        const { workId, language, title, description, audioUrl, isAutoGenerated } = req.body;

        // Verify work ownership to prevent cross-tenant translation upserts
        const work = await prisma.work.findUnique({ where: { id: workId } });
        if (!work) return res.status(404).json({ message: 'Obra não encontrada' });
        if (req.user!.role !== 'MASTER' && work.tenantId !== tenantId) {
            return res.status(403).json({ message: 'Sem permissão para esta obra' });
        }

        const translation = await prisma.workTranslation.upsert({
            where: { workId_language: { workId, language } },
            create: { workId, language, title, description, audioUrl, isAutoGenerated: isAutoGenerated ?? true, tenantId },
            update: { title, description, audioUrl, isAutoGenerated: isAutoGenerated ?? true }
        });
        res.json(translation);
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Erro ao salvar tradução' });
    }
});

// GET /translations/all — List all for admin
router.get('/all', authMiddleware, requireRole(['ADMIN', 'MASTER']), async (req, res) => {
    try {
        const tenantId = (req.user!.role === 'MASTER' && req.query.tenantId) ? (req.query.tenantId as string) : req.user!.tenantId;
        if (!tenantId) return res.status(400).json({ message: 'tenantId obrigatório' });

        const translations = await prisma.workTranslation.findMany({
            where: { tenantId },
            orderBy: [{ workId: 'asc' }, { language: 'asc' }]
        });

        // Group by work
        const grouped = new Map<string, any[]>();
        translations.forEach(t => {
            if (!grouped.has(t.workId)) grouped.set(t.workId, []);
            grouped.get(t.workId)!.push(t);
        });

        res.json({
            total: translations.length,
            languages: [...new Set(translations.map(t => t.language))],
            byWork: Object.fromEntries(grouped)
        });
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Erro ao listar traduções' });
    }
});

// DELETE /translations/:id
router.delete('/:id', authMiddleware, requireRole(['ADMIN', 'MASTER']), async (req, res) => {
    try {
        await assertTenantOwnership({ model: 'workTranslation', id: req.params.id, user: req.user! });

        await prisma.workTranslation.delete({ where: { id: req.params.id } });
        res.json({ message: 'Tradução excluída' });
    } catch (error: any) {
        if (error.status) return res.status(error.status).json({ message: error.message });
        console.error(error);
        res.status(500).json({ message: 'Erro ao excluir' });
    }
});

export default router;
